version: "2"
services:
    frontend:
        build: 
          context: ./frontend
          dockerfile: Dockerfile
        ports:
            - "80:80"

    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        ports:
            - "3050:3050"
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: storage
        volumes:
            - ./data-node:/data/db
        ports:
            - 27018:27018
        command: mongod --noauth --smallfiles


